"""
ctypes-based Python bindings for the cog0 C API.

Loads ``libcog0_capi`` and exposes an ``Agent`` class mirroring
``include/cog0/cog0_capi.h``.
"""

from __future__ import annotations

import ctypes
import os
import sys
from ctypes import (
    c_char_p,
    c_double,
    c_int,
    c_size_t,
    c_void_p,
)
from typing import Optional

from .exceptions import Cog0Error, Cog0LibraryNotFound, Cog0RuntimeError


def _candidate_lib_names():
    if sys.platform.startswith("linux"):
        return ["libcog0_capi.so", "cog0_capi.so"]
    if sys.platform == "darwin":
        return ["libcog0_capi.dylib", "cog0_capi.dylib"]
    if sys.platform == "win32":
        return ["cog0_capi.dll", "libcog0_capi.dll"]
    return ["libcog0_capi.so"]


def _candidate_lib_dirs():
    dirs = []
    env = os.environ.get("COG0_CAPI_LIB")
    if env:
        dirs.append(os.path.dirname(env) if os.path.isfile(env) else env)

    # Build-tree helper generated by CMake (file(GENERATE ... cog0_libpath.py))
    here = os.path.dirname(os.path.abspath(__file__))
    for rel in (
        os.path.join(here, "..", "..", "build", "agentzero-python-bridge"),
        os.path.join(here, "..", "build"),
        os.path.join(here, ".."),
        "/tmp/build-modules/agentzero-python-bridge",
        "/tmp/build-phase9/agentzero-python-bridge",
    ):
        dirs.append(os.path.abspath(rel))

    # Walk up looking for common build dirs
    root = os.path.abspath(os.path.join(here, "..", ".."))
    for name in ("build", "build-modules", "build-phase9", "build-standalone"):
        dirs.append(os.path.join(root, name, "agentzero-python-bridge"))
        dirs.append(os.path.join(root, name))

    # LD_LIBRARY_PATH / system paths
    for key in ("LD_LIBRARY_PATH", "DYLD_LIBRARY_PATH"):
        val = os.environ.get(key, "")
        dirs.extend([p for p in val.split(os.pathsep) if p])

    dirs.append("/usr/local/lib")
    dirs.append("/usr/lib")
    # de-dupe preserving order
    seen = set()
    out = []
    for d in dirs:
        if d and d not in seen:
            seen.add(d)
            out.append(d)
    return out


def _load_library():
    env = os.environ.get("COG0_CAPI_LIB")
    if env and os.path.isfile(env):
        return ctypes.CDLL(env)

    # Try importing CMake-generated path helper from build tree
    for d in _candidate_lib_dirs():
        helper = os.path.join(d, "cog0_libpath.py")
        if os.path.isfile(helper):
            ns = {}
            with open(helper, "r", encoding="utf-8") as f:
                exec(f.read(), ns)  # noqa: S102 — controlled build artifact
            lib_dir = ns.get("LIB_DIR")
            lib_name = ns.get("LIB_NAME")
            if lib_dir and lib_name:
                path = os.path.join(lib_dir, lib_name)
                if os.path.isfile(path):
                    return ctypes.CDLL(path)

    names = _candidate_lib_names()
    errors = []
    for d in _candidate_lib_dirs():
        for name in names:
            path = os.path.join(d, name)
            if os.path.isfile(path):
                try:
                    return ctypes.CDLL(path)
                except OSError as exc:
                    errors.append(f"{path}: {exc}")

    # Last resort: bare name (system loader path)
    for name in names:
        try:
            return ctypes.CDLL(name)
        except OSError as exc:
            errors.append(f"{name}: {exc}")

    raise Cog0LibraryNotFound(
        "Could not load libcog0_capi. Build agentzero-python-bridge or set "
        "COG0_CAPI_LIB to the shared library path. Tried:\n  "
        + "\n  ".join(errors[-8:])
    )


_lib = None


def _get_lib():
    global _lib
    if _lib is None:
        _lib = _load_library()
        _configure_prototypes(_lib)
    return _lib


def _configure_prototypes(lib) -> None:
    lib.cog0_agent_create.argtypes = [c_char_p, c_int, c_size_t]
    lib.cog0_agent_create.restype = c_void_p

    lib.cog0_agent_free.argtypes = [c_void_p]
    lib.cog0_agent_free.restype = None

    lib.cog0_agent_set_goal.argtypes = [c_void_p, c_char_p, c_char_p, c_double]
    lib.cog0_agent_set_goal.restype = c_int

    lib.cog0_agent_add_percept.argtypes = [c_void_p, c_char_p, c_char_p, c_double]
    lib.cog0_agent_add_percept.restype = None

    lib.cog0_agent_run_cycles.argtypes = [c_void_p, c_size_t]
    lib.cog0_agent_run_cycles.restype = None

    lib.cog0_agent_start.argtypes = [c_void_p]
    lib.cog0_agent_start.restype = None

    lib.cog0_agent_stop.argtypes = [c_void_p]
    lib.cog0_agent_stop.restype = None

    lib.cog0_agent_is_running.argtypes = [c_void_p]
    lib.cog0_agent_is_running.restype = c_int

    lib.cog0_agent_cycle_count.argtypes = [c_void_p]
    lib.cog0_agent_cycle_count.restype = c_size_t

    lib.cog0_agent_atom_count.argtypes = [c_void_p]
    lib.cog0_agent_atom_count.restype = c_size_t

    lib.cog0_agent_status_report.argtypes = [c_void_p]
    lib.cog0_agent_status_report.restype = ctypes.POINTER(ctypes.c_char)

    lib.cog0_agent_has_concept.argtypes = [c_void_p, c_char_p]
    lib.cog0_agent_has_concept.restype = c_int

    lib.cog0_agent_add_concept.argtypes = [c_void_p, c_char_p]
    lib.cog0_agent_add_concept.restype = None

    lib.cog0_version.argtypes = []
    lib.cog0_version.restype = c_char_p


def _b(s: Optional[str]) -> Optional[bytes]:
    if s is None:
        return None
    if isinstance(s, bytes):
        return s
    return s.encode("utf-8")


def version() -> str:
    """Return the cog0 library version string."""
    lib = _get_lib()
    v = lib.cog0_version()
    return v.decode("utf-8") if v else "unknown"


class Agent:
    """
    High-level Python wrapper around a cog0 agent handle.

    Parameters
    ----------
    name:
        Agent name (default ``\"cog0-agent\"``).
    cycle_interval_ms:
        Minimum milliseconds between background cycles.
    max_tasks_per_cycle:
        Maximum tasks executed per cognitive cycle.
    """

    def __init__(
        self,
        name: str = "cog0-agent",
        cycle_interval_ms: int = 10,
        max_tasks_per_cycle: int = 10,
    ) -> None:
        lib = _get_lib()
        handle = lib.cog0_agent_create(
            _b(name), int(cycle_interval_ms), c_size_t(max_tasks_per_cycle)
        )
        if not handle:
            raise Cog0RuntimeError("cog0_agent_create failed")
        self._handle = handle
        self._lib = lib

    def close(self) -> None:
        """Release the underlying C++ agent."""
        if getattr(self, "_handle", None):
            self._lib.cog0_agent_free(self._handle)
            self._handle = None

    def __del__(self) -> None:
        try:
            self.close()
        except Exception:
            pass

    def __enter__(self) -> "Agent":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.close()

    def _require(self) -> None:
        if not getattr(self, "_handle", None):
            raise Cog0Error("Agent handle is closed")

    def set_goal(self, name: str, description: str = "", priority: float = 0.5) -> None:
        self._require()
        ok = self._lib.cog0_agent_set_goal(
            self._handle, _b(name), _b(description), float(priority)
        )
        if not ok:
            raise Cog0RuntimeError(f"set_goal({name!r}) failed")

    def add_percept(self, source: str, content: str, salience: float = 0.5) -> None:
        self._require()
        self._lib.cog0_agent_add_percept(
            self._handle, _b(source), _b(content), float(salience)
        )

    def run_cycles(self, n: int = 1) -> None:
        self._require()
        self._lib.cog0_agent_run_cycles(self._handle, c_size_t(int(n)))

    def start(self) -> None:
        self._require()
        self._lib.cog0_agent_start(self._handle)

    def stop(self) -> None:
        self._require()
        self._lib.cog0_agent_stop(self._handle)

    @property
    def is_running(self) -> bool:
        self._require()
        return bool(self._lib.cog0_agent_is_running(self._handle))

    @property
    def cycle_count(self) -> int:
        self._require()
        return int(self._lib.cog0_agent_cycle_count(self._handle))

    @property
    def atom_count(self) -> int:
        self._require()
        return int(self._lib.cog0_agent_atom_count(self._handle))

    def status_report(self) -> str:
        self._require()
        ptr = self._lib.cog0_agent_status_report(self._handle)
        if not ptr:
            return ""
        try:
            return ctypes.cast(ptr, c_char_p).value.decode("utf-8")  # type: ignore[union-attr]
        finally:
            # Returned string is malloc'd by the C API.
            ctypes.CDLL(None).free(ptr)

    def has_concept(self, name: str) -> bool:
        self._require()
        return bool(self._lib.cog0_agent_has_concept(self._handle, _b(name)))

    def add_concept(self, name: str) -> None:
        self._require()
        self._lib.cog0_agent_add_concept(self._handle, _b(name))
