# -------------------------------------------------
# Library configuration

INCLUDE(GNUInstallDirs)

IF (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
	SET(CMAKE_MACOSX_RPATH 1)
ENDIF (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")

# Backwards compatibility: derive LIB_DIR_SUFFIX from CMAKE_INSTALL_LIBDIR
IF (NOT DEFINED LIB_DIR_SUFFIX)
	STRING(REGEX REPLACE "^lib" "" LIB_DIR_SUFFIX "${CMAKE_INSTALL_LIBDIR}")
ENDIF (NOT DEFINED LIB_DIR_SUFFIX)

# RPATH handling
SET(CMAKE_SKIP_BUILD_RPATH FALSE)
IF (APPLE)
	SET(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
ELSE (APPLE)
	SET(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
ENDIF (APPLE)
SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/opencog")
SET(CMAKE_BUILD_WITH_INSTALL_NAME_DIR FALSE)
SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
